spring.application.name=MeoSocial

spring.datasource.url=jdbc:mysql://localhost:3306/meosocial
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#Config max file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#Config JWT
app.jwtSecretKey=XoOXNLcTzDlQqjp2JzMNJ7+fi7UQ3O8FAselbtKQSgM=
app.jwtExpirationMs=86400000
#Config Redis Host
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60s
spring.data.redis.repositories.enabled=false
