spring:
  application:
    name: MeoSocial
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      repositories:
        enabled: 'false'
      host: ${DEV_ENV_REDIS_HOST}
      port: ${DEV_ENV_REDIS_PORT}
#      password: ${REDIS_PASSWORD}
      timeout: 60s
  datasource:
    url: ${DEV_ENV_MYSQL_DATABASE_URL}
    username: ${MYSQL_USER}
    password: ${DEV_ENV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
app:
  jwtSecretKey: ${JWT_SECRET_KEY}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}
  jwtRefreshExpirationMs: ${REFRESH_TOKEN_EXPIRATION_MS}
